const mongoose = require('mongoose')
const Campsite = require('./models/campsite')

/* automatically connects us to the nucampsite db in the mongo db server */
const url = 'mongodb://localhost:27017/nucampsite';

//this is a wrapper around the mongo db node drivers connect method
const connect = mongoose.connect(url, {
    //these are to deal with deprecation warnings from the mongo db driver
    useCreateIndex: true,
    useNewUrlParser: true,
    useUnifiedTopology: true
});

connect.then(() => {

    console.log('Connected correctly to server');

    //instantiate a new Campsite with the Campsite model
    const newCampsite = new Campsite({
        name: 'React Lake Campground',
        description: 'test'
    });

        /* save method is a mongoose method that saves the document to the database 
        (campsites) and
        returns a promise*/
    newCampsite.save()
    .then(campsite => {
        console.log(campsite);
        //find() finds all campsites based on the model
        return Campsite.find();
    })
    .then(campsites => {
        console.log(campsites);
        return Campsite.deleteMany();
    })
    .then(() => {
        return mongoose.connection.close();
    })
    .catch(err => {
        console.log(err);
        mongoose.connection.close();
    });
});


// Connected correctly to server
// {
//   _id: 639a9c6f39139b82984aad34, //auto generated by mongo db
//   name: 'React Lake Campground',
//   description: 'test',
//   createdAt: 2022-12-15T04:02:55.546Z, //auto generated by mongoose when timestamps is: true
//   updatedAt: 2022-12-15T04:02:55.546Z,
//   __v: 0  //used by mongoose for internal versioning
// }
// [
//   {
//     _id: 639a9c6f39139b82984aad34,
//     name: 'React Lake Campground',
//     description: 'test',
//     createdAt: 2022-12-15T04:02:55.546Z,
//     updatedAt: 2022-12-15T04:02:55.546Z,
//     __v: 0
//   }
// ]